# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'SwiftyCompanion' do

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Authentication
  # pod 'p2.OAuth2', '~> 2.2.0'
  pod 'p2.OAuth2', '~> 3.0'
  # Requests
  # pod 'Alamofire', '~> 3.5'
  pod 'Alamofire', '~> 4.0'
  # pod 'AlamofireImage', '~> 2.5'
  pod 'AlamofireImage', '~> 3.1'
  # UI

end

# Pods for SwiftyCompanion
# pod 'OAuthSwift', '~> 0.5.0'