export const authConstants = {
  _REQUEST: 'AUTH_',
  _SUCCESS: 'AUTH_',
  _FAILURE: 'AUTH_',

  REGISTER_REQUEST: 'AUTH_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'AUTH_REGISTER_FAILURE',

  FORGOT_PASSWORD_REQUEST: 'AUTH_FORGOT_PASSWORD_REQUEST',
  FORGOT_PASSWORD_SUCCESS: 'AUTH_FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_FAILURE: 'AUTH_FORGOT_PASSWORD_FAILURE',

  CHANGE_PASSWORD_REQUEST: 'AUTH_CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCESS: 'AUTH_CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'AUTH_CHANGE_PASSWORD_FAILURE',

  ACTIVATE_ACCOUNT_REQUEST: 'AUTH_ACTIVATE_ACCOUNT_REQUEST',
  ACTIVATE_ACCOUNT_SUCCESS: 'AUTH_ACTIVATE_ACCOUNT_SUCCESS',
  ACTIVATE_ACCOUNT_FAILURE: 'AUTH_ACTIVATE_ACCOUNT_FAILURE',

  LOGIN_REQUEST: 'AUTH_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',

  OAUTH_LOGIN_REQUEST: 'AUTH_OAUTH_LOGIN_REQUEST',
  OAUTH_LOGIN_SUCCESS: 'AUTH_OAUTH_LOGIN_SUCCESS',
  OAUTH_LOGIN_FAILURE: 'AUTH_OAUTH_LOGIN_FAILURE',

  LOGOUT_REQUEST: 'AUTH_LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'AUTH_LOGOUT_FAILURE'
}
