export const userConstants = {
  _FAILURE: 'USER__FAILURE',
  _REQUEST: 'USER__REQUEST',
  _SUCCESS: 'USER__SUCCESS',

  BLOCK_INTERACTION_FAILURE: 'USER_BLOCK_INTERACTION_FAILURE',
  BLOCK_INTERACTION_REQUEST: 'USER_BLOCK_INTERACTION_REQUEST',
  BLOCK_INTERACTION_SUCCESS: 'USER_BLOCK_INTERACTION_SUCCESS',

  GET_BASE_INFOS_FAILURE: 'USER_GET_BASE_INFOS_FAILURE',
  GET_BASE_INFOS_REQUEST: 'USER_GET_BASE_INFOS_REQUEST',
  GET_BASE_INFOS_SUCCESS: 'USER_GET_BASE_INFOS_SUCCESS',

  LIKE_INTERACTION_FAILURE: 'USER_LIKE_INTERACTION_FAILURE',
  LIKE_INTERACTION_REQUEST: 'USER_LIKE_INTERACTION_REQUEST',
  LIKE_INTERACTION_SUCCESS: 'USER_LIKE_INTERACTION_SUCCESS',

  LIST_ALL_USERS_FAILURE: 'USER_LIST_ALL_USERS_FAILURE',
  LIST_ALL_USERS_REQUEST: 'USER_LIST_ALL_USERS_REQUEST',
  LIST_ALL_USERS_SUCCESS: 'USER_LIST_ALL_USERS_SUCCESS',

  LIST_INFOS_FAILURE: 'USER_LIST_INFOS_FAILURE',
  LIST_INFOS_REQUEST: 'USER_LIST_INFOS_REQUEST',
  LIST_INFOS_SUCCESS: 'USER_LIST_INFOS_SUCCESS',

  LIST_INFOS_FROM_FAILURE: 'USER_LIST_INFOS_FROM_FAILURE',
  LIST_INFOS_FROM_REQUEST: 'USER_LIST_INFOS_FROM_REQUEST',
  LIST_INFOS_FROM_SUCCESS: 'USER_LIST_INFOS_FROM_SUCCESS',

  LIST_MESSAGES_FAILURE: 'USER_LIST_MESSAGES_FAILURE',
  LIST_MESSAGES_REQUEST: 'USER_LIST_MESSAGES_REQUEST',
  LIST_MESSAGES_SUCCESS: 'USER_LIST_MESSAGES_SUCCESS',

  LIST_MESSAGES_FROM_FAILURE: 'USER_LIST_MESSAGES_FROM_FAILURE',
  LIST_MESSAGES_FROM_REQUEST: 'USER_LIST_MESSAGES_FROM_REQUEST',
  LIST_MESSAGES_FROM_SUCCESS: 'USER_LIST_MESSAGES_FROM_SUCCESS',

  LOGOUT_FAILURE: 'USER_LOGOUT_FAILURE',
  LOGOUT_REQUEST: 'USER_LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',

  REFRESH_GUESTS_FAILURE: 'USER_REFRESH_GUESTS_FAILURE',
  REFRESH_GUESTS_REQUEST: 'USER_REFRESH_GUESTS_REQUEST',
  REFRESH_GUESTS_SUCCESS: 'USER_REFRESH_GUESTS_SUCCESS',

  REFRESH_MESSAGES_FROM_FAILURE: 'USER_REFRESH_MESSAGES_FROM_FAILURE',
  REFRESH_MESSAGES_FROM_REQUEST: 'USER_REFRESH_MESSAGES_FROM_REQUEST',
  REFRESH_MESSAGES_FROM_SUCCESS: 'USER_REFRESH_MESSAGES_FROM_SUCCESS',

  REFRESH_NOTIFICATIONS_FAILURE: 'USER_REFRESH_NOTIFICATIONS_FAILURE',
  REFRESH_NOTIFICATIONS_REQUEST: 'USER_REFRESH_NOTIFICATIONS_REQUEST',
  REFRESH_NOTIFICATIONS_SUCCESS: 'USER_REFRESH_NOTIFICATIONS_SUCCESS',

  REPORT_INTERACTION_FAILURE: 'USER_REPORT_INTERACTION_FAILURE',
  REPORT_INTERACTION_REQUEST: 'USER_REPORT_INTERACTION_REQUEST',
  REPORT_INTERACTION_SUCCESS: 'USER_REPORT_INTERACTION_SUCCESS',

  SUGGEST_USERS_FAILURE: 'USER_SUGGEST_USERS_FAILURE',
  SUGGEST_USERS_REQUEST: 'USER_SUGGEST_USERS_REQUEST',
  SUGGEST_USERS_SUCCESS: 'USER_SUGGEST_USERS_SUCCESS',

  TALK_INTERACTION_FAILURE: 'USER_TALK_INTERACTION_FAILURE',
  TALK_INTERACTION_REQUEST: 'USER_TALK_INTERACTION_REQUEST',
  TALK_INTERACTION_SUCCESS: 'USER_TALK_INTERACTION_SUCCESS',

  UNBLOCK_INTERACTION_FAILURE: 'USER_UNBLOCK_INTERACTION_FAILURE',
  UNBLOCK_INTERACTION_REQUEST: 'USER_UNBLOCK_INTERACTION_REQUEST',
  UNBLOCK_INTERACTION_SUCCESS: 'USER_UNBLOCK_INTERACTION_SUCCESS',

  UNLIKE_INTERACTION_FAILURE: 'USER_UNLIKE_INTERACTION_FAILURE',
  UNLIKE_INTERACTION_REQUEST: 'USER_UNLIKE_INTERACTION_REQUEST',
  UNLIKE_INTERACTION_SUCCESS: 'USER_UNLIKE_INTERACTION_SUCCESS',

  UPDATE_COORDS_FAILURE: 'USER_UPDATE_COORDS_FAILURE',
  UPDATE_COORDS_REQUEST: 'USER_UPDATE_COORDS_REQUEST',
  UPDATE_COORDS_SUCCESS: 'USER_UPDATE_COORDS_SUCCESS',

  UPDATE_EMAIL_FAILURE: 'USER_UPDATE_EMAIL_FAILURE',
  UPDATE_EMAIL_REQUEST: 'USER_UPDATE_EMAIL_REQUEST',
  UPDATE_EMAIL_SUCCESS: 'USER_UPDATE_EMAIL_SUCCESS',

  UPDATE_INTERESTS_FAILURE: 'USER_UPDATE_INTERESTS_FAILURE',
  UPDATE_INTERESTS_REQUEST: 'USER_UPDATE_INTERESTS_REQUEST',
  UPDATE_INTERESTS_SUCCESS: 'USER_UPDATE_INTERESTS_SUCCESS',

  UPDATE_MESSAGES_FROM_FAILURE: 'USER_UPDATE_MESSAGES_FROM_FAILURE',
  UPDATE_MESSAGES_FROM_REQUEST: 'USER_UPDATE_MESSAGES_FROM_REQUEST',
  UPDATE_MESSAGES_FROM_SUCCESS: 'USER_UPDATE_MESSAGES_FROM_SUCCESS',

  UPDATE_NOTIFICATIONS_FAILURE: 'USER_UPDATE_NOTIFICATIONS_FAILURE',
  UPDATE_NOTIFICATIONS_REQUEST: 'USER_UPDATE_NOTIFICATIONS_REQUEST',
  UPDATE_NOTIFICATIONS_SUCCESS: 'USER_UPDATE_NOTIFICATIONS_SUCCESS',

  UPDATE_PASSWORD_FAILURE: 'USER_UPDATE_PASSWORD_FAILURE',
  UPDATE_PASSWORD_REQUEST: 'USER_UPDATE_PASSWORD_REQUEST',
  UPDATE_PASSWORD_SUCCESS: 'USER_UPDATE_PASSWORD_SUCCESS',

  UPDATE_PHOTOS_FAILURE: 'USER_UPDATE_PHOTOS_FAILURE',
  UPDATE_PHOTOS_REQUEST: 'USER_UPDATE_PHOTOS_REQUEST',
  UPDATE_PHOTOS_SUCCESS: 'USER_UPDATE_PHOTOS_SUCCESS',

  UPDATE_PROFILE_FAILURE: 'USER_UPDATE_PROFILE_FAILURE',
  UPDATE_PROFILE_REQUEST: 'USER_UPDATE_PROFILE_REQUEST',
  UPDATE_PROFILE_SUCCESS: 'USER_UPDATE_PROFILE_SUCCESS',

  UPDATE_PROFILE_PHOTO_FAILURE: 'USER_UPDATE_PROFILE_PHOTO_FAILURE',
  UPDATE_PROFILE_PHOTO_REQUEST: 'USER_UPDATE_PROFILE_PHOTO_REQUEST',
  UPDATE_PROFILE_PHOTO_SUCCESS: 'USER_UPDATE_PROFILE_PHOTO_SUCCESS',

  VIEW_INTERACTION_FAILURE: 'USER_VIEW_INTERACTION_FAILURE',
  VIEW_INTERACTION_REQUEST: 'USER_VIEW_INTERACTION_REQUEST',
  VIEW_INTERACTION_SUCCESS: 'USER_VIEW_INTERACTION_SUCCESS'
}
